Remove patches not needed in qt 5.9.4 and add macOS 10.9 support

diff --git a/recipe/0011-osx-allow-any-xcrun-in-PATH.patch b/recipe/0011-osx-allow-any-xcrun-in-PATH.patch
--- a/recipe/0011-osx-allow-any-xcrun-in-PATH.patch
+++ b/recipe/0011-osx-allow-any-xcrun-in-PATH.patch
@@ -1,7 +1,16 @@
-diff -urN qtbase.orig/configure qtbase/configure
---- qtbase.orig/configure	2017-08-31 03:18:33.000000000 -0700
-+++ qtbase/configure	2017-08-31 03:19:07.000000000 -0700
-@@ -315,7 +315,7 @@
+diff -urN work_failed_provide.orig/qtbase/configure work_failed_provide/qtbase/configure
+--- work_failed_provide.orig/qtbase/configure	2018-02-13 10:11:01.000000000 +0000
++++ work_failed_provide/qtbase/configure	2018-02-13 10:16:59.000000000 +0000
+@@ -232,7 +232,7 @@
+ 
+     sdk=$(getSingleQMakeVariable "QMAKE_MAC_SDK" "$1")
+     if [ -z "$sdk" ]; then echo "QMAKE_MAC_SDK must be set when building on Mac" >&2; exit 1; fi
+-    sysroot=$(/usr/bin/xcrun --sdk $sdk --show-sdk-path 2>/dev/null)
++    sysroot=$(xcrun --sdk $sdk --show-sdk-path 2>/dev/null)
+     if [ -z "$sysroot" ]; then echo "Failed to resolve SDK path for '$sdk'" >&2; exit 1; fi
+ 
+     case "$sdk" in
+@@ -267,7 +267,7 @@
                  # Prefix tool with toolchain path
                  var=$(echo "$line" | cut -d '=' -f 1)
                  val=$(echo "$line" | cut -d '=' -f 2-)
@@ -10,40 +19,53 @@ diff -urN qtbase.orig/configure qtbase/configure
                  val=$(echo $sdk_val $(echo $val | cut -s -d ' ' -f 2-))
                  echo "$var=$val"
              ;;
-@@ -543,7 +543,7 @@
-         exit 2
+@@ -329,8 +329,8 @@
      fi
  
--    if ! /usr/bin/xcrun -find xcodebuild >/dev/null 2>&1; then
-+    if ! xcrun -find xcodebuild >/dev/null 2>&1; then
-         echo >&2
-         echo "   Xcode not set up properly. You may need to confirm the license" >&2
-         echo "   agreement by running /usr/bin/xcodebuild without arguments." >&2
-@@ -2831,7 +2831,7 @@
-         # about the OS version, since we're not using the clang version that comes
-         # with the system. We use 'xcrun' to check the clang version that's part of
-         # the Xcode installation.
--        XCRUN=`/usr/bin/xcrun -sdk macosx clang -v 2>&1`
-+        XCRUN=`xcrun -sdk macosx clang -v 2>&1`
-         CLANGVERSION=`echo "$XCRUN" | sed -n 's/.*version \([0-9]\).*/\1/p'`
-         expr "$CLANGVERSION" : '[0-9]' > /dev/null || { echo "Unable to determine CLANG version from output of xcrun: $XCRUN" ; exit 2 ; }
-         if [ "$CLANGVERSION" -ge 3 ]; then
-diff -urN qtbase.orig/mkspecs/features/mac/default_pre.prf qtbase/mkspecs/features/mac/default_pre.prf
---- qtbase.orig/mkspecs/features/mac/default_pre.prf	2017-08-31 03:18:35.000000000 -0700
-+++ qtbase/mkspecs/features/mac/default_pre.prf	2017-08-31 03:19:22.000000000 -0700
-@@ -12,7 +12,7 @@
-         error("Xcode is not installed in $${QMAKE_XCODE_DEVELOPER_PATH}. Please use xcode-select to choose Xcode installation path.")
- 
-     # Make sure Xcode is set up properly
--    isEmpty($$list($$system("/usr/bin/xcrun -find xcodebuild 2>/dev/null"))): \
-+    isEmpty($$list($$system("xcrun -find xcodebuild 2>/dev/null"))): \
-         error("Xcode not set up properly. You may need to confirm the license agreement by running /usr/bin/xcodebuild.")
+     # In the else case we are probably using a Command Line Tools installation
+-    if /usr/bin/xcrun -find xcodebuild >/dev/null 2>&1; then
+-        if ! /usr/bin/xcrun xcodebuild -license check 2>/dev/null; then
++    if xcrun -find xcodebuild >/dev/null 2>&1; then
++        if ! xcrun xcodebuild -license check 2>/dev/null; then
+             echo >&2
+             echo "   Xcode setup not complete. You need to confirm the license" >&2
+             echo "   agreement by running 'sudo xcrun xcodebuild -license accept'." >&2
+diff -urN work_failed_provide.orig/qtbase/mkspecs/features/mac/default_pre.prf work_failed_provide/qtbase/mkspecs/features/mac/default_pre.prf
+--- work_failed_provide.orig/qtbase/mkspecs/features/mac/default_pre.prf	2018-02-13 10:11:01.000000000 +0000
++++ work_failed_provide/qtbase/mkspecs/features/mac/default_pre.prf	2018-02-13 10:17:26.000000000 +0000
+@@ -13,16 +13,16 @@
  }
  
-diff -urN qtbase.orig/mkspecs/features/mac/sdk.prf qtbase/mkspecs/features/mac/sdk.prf
---- qtbase.orig/mkspecs/features/mac/sdk.prf	2017-08-31 03:18:35.000000000 -0700
-+++ qtbase/mkspecs/features/mac/sdk.prf	2017-08-31 03:19:38.000000000 -0700
-@@ -52,7 +52,7 @@
+ isEmpty(QMAKE_XCODEBUILD_PATH): \
+-    QMAKE_XCODEBUILD_PATH = $$system("/usr/bin/xcrun -find xcodebuild 2>/dev/null")
++    QMAKE_XCODEBUILD_PATH = $$system("xcrun -find xcodebuild 2>/dev/null")
+ 
+ !isEmpty(QMAKE_XCODEBUILD_PATH) {
+     # Make sure Xcode is set up properly
+-    !system("/usr/bin/xcrun xcodebuild -license check 2>/dev/null"): \
++    !system("xcrun xcodebuild -license check 2>/dev/null"): \
+         error("Xcode not set up properly. You need to confirm the license agreement by running 'sudo xcrun xcodebuild -license accept'.")
+ 
+     isEmpty(QMAKE_XCODE_VERSION) {
+         # Extract Xcode version using xcodebuild
+-        xcode_version = $$system("/usr/bin/xcrun xcodebuild -version")
++        xcode_version = $$system("xcrun xcodebuild -version")
+         QMAKE_XCODE_VERSION = $$member(xcode_version, 1)
+         isEmpty(QMAKE_XCODE_VERSION): error("Could not resolve Xcode version.")
+         unset(xcode_version)
+diff -urN work_failed_provide.orig/qtbase/mkspecs/features/mac/sdk.prf work_failed_provide/qtbase/mkspecs/features/mac/sdk.prf
+--- work_failed_provide.orig/qtbase/mkspecs/features/mac/sdk.prf	2018-02-13 10:11:01.000000000 +0000
++++ work_failed_provide/qtbase/mkspecs/features/mac/sdk.prf	2018-02-13 10:17:08.000000000 +0000
+@@ -18,7 +18,7 @@
+         sdk = $$QMAKE_MAC_SDK
+ 
+     isEmpty(QMAKE_MAC_SDK.$${sdk}.$${info}) {
+-        QMAKE_MAC_SDK.$${sdk}.$${info} = $$system("/usr/bin/xcrun --sdk $$sdk $$info 2>/dev/null")
++        QMAKE_MAC_SDK.$${sdk}.$${info} = $$system("xcrun --sdk $$sdk $$info 2>/dev/null")
+         # --show-sdk-platform-path won't work for Command Line Tools; this is fine
+         # only used by the XCTest backend to testlib
+         isEmpty(QMAKE_MAC_SDK.$${sdk}.$${info}):if(!isEmpty(QMAKE_XCODEBUILD_PATH)|!equals(info, "--show-sdk-platform-path")): \
+@@ -50,7 +50,7 @@
      value = $$eval($$tool)
      isEmpty(value): next()
  
@@ -52,57 +74,3 @@ diff -urN qtbase.orig/mkspecs/features/mac/sdk.prf qtbase/mkspecs/features/mac/s
      isEmpty(sysrooted): next()
  
      $$tool = $$sysrooted $$member(value, 1, -1)
-diff -urN qtbase.orig/configure qtbase/configure
---- qtbase.orig/configure	2017-08-31 04:18:52.000000000 -0700
-+++ qtbase/configure	2017-08-31 04:24:36.000000000 -0700
-@@ -292,7 +292,7 @@
- 
-     sdk=$(getSingleQMakeVariable "QMAKE_MAC_SDK" "$1")
-     if [ -z "$sdk" ]; then echo "QMAKE_MAC_SDK must be set when building on Mac" >&2; exit 1; fi
--    sysroot=$(/usr/bin/xcodebuild -sdk $sdk -version Path 2>/dev/null)
-+    sysroot=$(xcodebuild -sdk $sdk -version Path 2>/dev/null)
-     if [ -z "$sysroot" ]; then echo "Failed to resolve SDK path for '$sdk'" >&2; exit 1; fi
- 
-     case "$sdk" in
-diff -urN qtbase.orig/mkspecs/features/mac/sdk.prf qtbase/mkspecs/features/mac/sdk.prf
---- qtbase.orig/mkspecs/features/mac/sdk.prf	2017-08-31 04:18:57.000000000 -0700
-+++ qtbase/mkspecs/features/mac/sdk.prf	2017-08-31 04:29:06.000000000 -0700
-@@ -6,7 +6,7 @@
-     error("QMAKE_MAC_SDK can only contain short-form SDK names (eg. macosx, iphoneos)")
- 
- isEmpty(QMAKE_MAC_SDK.$${QMAKE_MAC_SDK}.path) {
--    QMAKE_MAC_SDK_PATH = $$system("/usr/bin/xcodebuild -sdk $$QMAKE_MAC_SDK -version Path 2>/dev/null")
-+    QMAKE_MAC_SDK_PATH = $$system("xcodebuild -sdk $$QMAKE_MAC_SDK -version Path 2>/dev/null")
-     isEmpty(QMAKE_MAC_SDK_PATH): error("Could not resolve SDK path for \'$$QMAKE_MAC_SDK\'")
-     cache(QMAKE_MAC_SDK.$${QMAKE_MAC_SDK}.path, set stash, QMAKE_MAC_SDK_PATH)
- } else {
-@@ -14,7 +14,7 @@
- }
- 
- isEmpty(QMAKE_MAC_SDK.$${QMAKE_MAC_SDK}.platform_path) {
--    QMAKE_MAC_SDK_PLATFORM_PATH = $$system("/usr/bin/xcodebuild -sdk $$QMAKE_MAC_SDK -version PlatformPath 2>/dev/null")
-+    QMAKE_MAC_SDK_PLATFORM_PATH = $$system("xcodebuild -sdk $$QMAKE_MAC_SDK -version PlatformPath 2>/dev/null")
-     isEmpty(QMAKE_MAC_SDK_PLATFORM_PATH): error("Could not resolve SDK platform path for \'$$QMAKE_MAC_SDK\'")
-     cache(QMAKE_MAC_SDK.$${QMAKE_MAC_SDK}.platform_path, set stash, QMAKE_MAC_SDK_PLATFORM_PATH)
- } else {
-@@ -22,7 +22,7 @@
- }
- 
- isEmpty(QMAKE_MAC_SDK.$${QMAKE_MAC_SDK}.version) {
--    QMAKE_MAC_SDK_VERSION = $$system("/usr/bin/xcodebuild -sdk $$QMAKE_MAC_SDK -version SDKVersion 2>/dev/null")
-+    QMAKE_MAC_SDK_VERSION = $$system("xcodebuild -sdk $$QMAKE_MAC_SDK -version SDKVersion 2>/dev/null")
-     isEmpty(QMAKE_MAC_SDK_VERSION): error("Could not resolve SDK version for \'$$QMAKE_MAC_SDK\'")
-     cache(QMAKE_MAC_SDK.$${QMAKE_MAC_SDK}.version, set stash, QMAKE_MAC_SDK_VERSION)
- } else {
-diff -urN qtbase.orig/mkspecs/features/mac/default_pre.prf qtbase/mkspecs/features/mac/default_pre.prf
---- qtbase.orig/mkspecs/features/mac/default_pre.prf	2017-08-31 04:46:10.000000000 -0700
-+++ qtbase/mkspecs/features/mac/default_pre.prf	2017-08-31 04:46:32.000000000 -0700
-@@ -18,7 +18,7 @@
- 
- isEmpty(QMAKE_XCODE_VERSION) {
-     # Extract Xcode version using xcodebuild
--    xcode_version = $$system("/usr/bin/xcodebuild -version")
-+    xcode_version = $$system("xcodebuild -version")
-     QMAKE_XCODE_VERSION = $$member(xcode_version, 1)
-     isEmpty(QMAKE_XCODE_VERSION): error("Could not resolve Xcode version.")
-     unset(xcode_version)
