More patches, clang 4 compat. this time

diff --git a/recipe/0011-osx-allow-any-xcrun-in-PATH.patch b/recipe/0011-osx-allow-any-xcrun-in-PATH.patch
--- a/recipe/0011-osx-allow-any-xcrun-in-PATH.patch
+++ b/recipe/0011-osx-allow-any-xcrun-in-PATH.patch
@@ -52,3 +52,57 @@ diff -urN qtbase.orig/mkspecs/features/mac/sdk.prf qtbase/mkspecs/features/mac/s
      isEmpty(sysrooted): next()
  
      $$tool = $$sysrooted $$member(value, 1, -1)
+diff -urN qtbase.orig/configure qtbase/configure
+--- qtbase.orig/configure	2017-08-31 04:18:52.000000000 -0700
++++ qtbase/configure	2017-08-31 04:24:36.000000000 -0700
+@@ -292,7 +292,7 @@
+ 
+     sdk=$(getSingleQMakeVariable "QMAKE_MAC_SDK" "$1")
+     if [ -z "$sdk" ]; then echo "QMAKE_MAC_SDK must be set when building on Mac" >&2; exit 1; fi
+-    sysroot=$(/usr/bin/xcodebuild -sdk $sdk -version Path 2>/dev/null)
++    sysroot=$(xcodebuild -sdk $sdk -version Path 2>/dev/null)
+     if [ -z "$sysroot" ]; then echo "Failed to resolve SDK path for '$sdk'" >&2; exit 1; fi
+ 
+     case "$sdk" in
+diff -urN qtbase.orig/mkspecs/features/mac/sdk.prf qtbase/mkspecs/features/mac/sdk.prf
+--- qtbase.orig/mkspecs/features/mac/sdk.prf	2017-08-31 04:18:57.000000000 -0700
++++ qtbase/mkspecs/features/mac/sdk.prf	2017-08-31 04:29:06.000000000 -0700
+@@ -6,7 +6,7 @@
+     error("QMAKE_MAC_SDK can only contain short-form SDK names (eg. macosx, iphoneos)")
+ 
+ isEmpty(QMAKE_MAC_SDK.$${QMAKE_MAC_SDK}.path) {
+-    QMAKE_MAC_SDK_PATH = $$system("/usr/bin/xcodebuild -sdk $$QMAKE_MAC_SDK -version Path 2>/dev/null")
++    QMAKE_MAC_SDK_PATH = $$system("xcodebuild -sdk $$QMAKE_MAC_SDK -version Path 2>/dev/null")
+     isEmpty(QMAKE_MAC_SDK_PATH): error("Could not resolve SDK path for \'$$QMAKE_MAC_SDK\'")
+     cache(QMAKE_MAC_SDK.$${QMAKE_MAC_SDK}.path, set stash, QMAKE_MAC_SDK_PATH)
+ } else {
+@@ -14,7 +14,7 @@
+ }
+ 
+ isEmpty(QMAKE_MAC_SDK.$${QMAKE_MAC_SDK}.platform_path) {
+-    QMAKE_MAC_SDK_PLATFORM_PATH = $$system("/usr/bin/xcodebuild -sdk $$QMAKE_MAC_SDK -version PlatformPath 2>/dev/null")
++    QMAKE_MAC_SDK_PLATFORM_PATH = $$system("xcodebuild -sdk $$QMAKE_MAC_SDK -version PlatformPath 2>/dev/null")
+     isEmpty(QMAKE_MAC_SDK_PLATFORM_PATH): error("Could not resolve SDK platform path for \'$$QMAKE_MAC_SDK\'")
+     cache(QMAKE_MAC_SDK.$${QMAKE_MAC_SDK}.platform_path, set stash, QMAKE_MAC_SDK_PLATFORM_PATH)
+ } else {
+@@ -22,7 +22,7 @@
+ }
+ 
+ isEmpty(QMAKE_MAC_SDK.$${QMAKE_MAC_SDK}.version) {
+-    QMAKE_MAC_SDK_VERSION = $$system("/usr/bin/xcodebuild -sdk $$QMAKE_MAC_SDK -version SDKVersion 2>/dev/null")
++    QMAKE_MAC_SDK_VERSION = $$system("xcodebuild -sdk $$QMAKE_MAC_SDK -version SDKVersion 2>/dev/null")
+     isEmpty(QMAKE_MAC_SDK_VERSION): error("Could not resolve SDK version for \'$$QMAKE_MAC_SDK\'")
+     cache(QMAKE_MAC_SDK.$${QMAKE_MAC_SDK}.version, set stash, QMAKE_MAC_SDK_VERSION)
+ } else {
+diff -urN qtbase.orig/mkspecs/features/mac/default_pre.prf qtbase/mkspecs/features/mac/default_pre.prf
+--- qtbase.orig/mkspecs/features/mac/default_pre.prf	2017-08-31 04:46:10.000000000 -0700
++++ qtbase/mkspecs/features/mac/default_pre.prf	2017-08-31 04:46:32.000000000 -0700
+@@ -18,7 +18,7 @@
+ 
+ isEmpty(QMAKE_XCODE_VERSION) {
+     # Extract Xcode version using xcodebuild
+-    xcode_version = $$system("/usr/bin/xcodebuild -version")
++    xcode_version = $$system("xcodebuild -version")
+     QMAKE_XCODE_VERSION = $$member(xcode_version, 1)
+     isEmpty(QMAKE_XCODE_VERSION): error("Could not resolve Xcode version.")
+     unset(xcode_version)
